version: '3.4'

services:
  receptionbook.api:
    image: ${DOCKER_REGISTRY-}receptionbookapi
    build:
      context: .
      dockerfile: ReceptionBook.API/Dockerfile
    depends_on:
      - receptionbook.db

  receptionbook.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - receptionbook.db-data:/var/opt/mssql

volumes:
  receptionbook.db-data:
