version: '3.4'

services:
  receptionbook:
    image: ${DOCKER_REGISTRY-}receptionbook
    build:
      context: .
      dockerfile: ReceptionBook/Dockerfile
    depends_on:
      - db
    ports:
     - "5000:8080"
     - "5001:8081"

  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
