version: '3.4'

services:
  receptionbook:
    image: ${DOCKER_REGISTRY-}receptionbook
    build:
      context: .
      dockerfile: ReceptionBook/Dockerfile
    depends_on:
      - db
    ports:
     - "5000:8080"
     - "5001:8081"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
